package com.baafoo.core.util;

import com.baafoo.core.model.ChaosProfile;
import com.baafoo.core.model.ChaosProfile.ChaosRule;
import com.baafoo.core.model.FaultInjection;
import com.baafoo.core.model.MatchCondition;
import com.baafoo.core.model.ResponseEntry;
import com.baafoo.core.model.Rule;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Pattern;

/**
 * Chaos engineering profile manager (PRD §6 R-S13).
 *
 * <p>Manages the lifecycle of Chaos profiles: loading from config, activating
 * (generating and tracking fault injection rules), deactivating, and emergency
 * stop. Thread-safe via ConcurrentHashMap for active profile tracking.</p>
 *
 * <p>Profile activation generates Baafoo {@link Rule}s with fault injection
 * configs. The generated rule IDs follow the pattern
 * {@code chaos-{profileName}-{ruleIndex}} for easy identification and cleanup.</p>
 */
public class ChaosManager {

    /** Prefix for rule IDs generated by Chaos profiles */
    public static final String CHAOS_RULE_ID_PREFIX = "chaos-";

    /**
     * Allowed characters for profile names: {@code [a-zA-Z0-9_-]}.
     * Prevents malformed rule IDs ({@code chaos-{profileName}-{index}})
     * that could break URL routing or storage layer lookups (S8 fix).
     */
    private static final Pattern VALID_PROFILE_NAME = Pattern.compile("[a-zA-Z0-9_-]+");

    private final Map<String, ChaosProfile> profiles = new ConcurrentHashMap<String, ChaosProfile>();
    private final Set<String> activeProfileNames = Collections.newSetFromMap(
            new ConcurrentHashMap<String, Boolean>());

    /**
     * Register a Chaos profile.
     *
     * @param profile the profile to register; replaces any existing profile with the same name
     * @throws IllegalArgumentException if profile/name is null/empty or name contains
     *         characters outside {@code [a-zA-Z0-9_-]}
     */
    public void registerProfile(ChaosProfile profile) {
        if (profile == null || profile.getName() == null || profile.getName().isEmpty()) {
            throw new IllegalArgumentException("Profile name must not be null or empty");
        }
        validateProfileName(profile.getName());
        profiles.put(profile.getName(), profile);
    }

    /**
     * Validate that a profile name contains only safe characters {@code [a-zA-Z0-9_-]}.
     */
    private static void validateProfileName(String name) {
        if (!VALID_PROFILE_NAME.matcher(name).matches()) {
            throw new IllegalArgumentException(
                    "Invalid profile name '" + name + "': only [a-zA-Z0-9_-] are allowed");
        }
    }

    /**
     * Register multiple profiles at once.
     */
    public void registerProfiles(List<ChaosProfile> profileList) {
        if (profileList == null) return;
        for (ChaosProfile profile : profileList) {
            registerProfile(profile);
        }
    }

    /**
     * Get a registered profile by name.
     */
    public ChaosProfile getProfile(String name) {
        return profiles.get(name);
    }

    /**
     * List all registered profiles.
     */
    public List<ChaosProfile> listProfiles() {
        return new ArrayList<ChaosProfile>(profiles.values());
    }

    /**
     * Activate a Chaos profile, generating fault injection rules.
     *
     * <p>For each {@link ChaosRule} in the profile, a Baafoo {@link Rule} is
     * generated with:
     * <ul>
     *   <li>ID: {@code chaos-{profileName}-{index}}</li>
     *   <li>Conditions: method + path (regex)</li>
     *   <li>Fault injection: from the Chaos rule</li>
     *   <li>Environments: from the profile</li>
     *   <li>A default 200 response (in case no fault triggers)</li>
     * </ul>
     * </p>
     *
     * @param profileName the name of the profile to activate
     * @return list of generated rules (empty if profile not found or already active)
     */
    public synchronized ActivateResult activate(String profileName) {
        ChaosProfile profile = profiles.get(profileName);
        if (profile == null) {
            return ActivateResult.notFound(profileName);
        }

        // Atomic check-then-act: add() returns false if already present,
        // eliminating the race between contains() and add() (S5 fix).
        if (!activeProfileNames.add(profileName)) {
            return ActivateResult.alreadyActive(profileName);
        }

        List<Rule> generatedRules = new ArrayList<Rule>();
        List<ChaosRule> chaosRules = profile.getRules();
        if (chaosRules != null) {
            for (int i = 0; i < chaosRules.size(); i++) {
                ChaosRule chaosRule = chaosRules.get(i);
                Rule rule = generateRule(profile, chaosRule, i);
                generatedRules.add(rule);
            }
        }

        return ActivateResult.success(profileName, generatedRules);
    }

    /**
     * Deactivate a Chaos profile.
     *
     * @param profileName the name of the profile to deactivate
     * @return list of rule IDs that were generated by this profile (for cleanup)
     */
    public DeactivateResult deactivate(String profileName) {
        // Atomic check-then-act: remove() returns false if not present,
        // eliminating the race between contains() and remove() (S6 fix).
        if (!activeProfileNames.remove(profileName)) {
            return DeactivateResult.notActive(profileName);
        }

        ChaosProfile profile = profiles.get(profileName);
        List<String> ruleIds = new ArrayList<String>();
        if (profile != null && profile.getRules() != null) {
            for (int i = 0; i < profile.getRules().size(); i++) {
                ruleIds.add(generateRuleId(profileName, i));
            }
        }

        return DeactivateResult.success(profileName, ruleIds);
    }

    /**
     * Emergency stop: deactivate all active Chaos profiles.
     *
     * <p>The snapshot is taken and processed under a {@code synchronized} lock
     * to prevent two concurrent emergency-stop calls from both returning the
     * same rule IDs. Individual {@code remove()} calls (instead of
     * {@code clear()}) ensure that a concurrent {@link #activate(String)} that
     * adds a new profile after the snapshot is NOT silently wiped, avoiding
     * orphan rules (S7 fix).</p>
     *
     * @return list of all rule IDs generated by active profiles (for cleanup)
     */
    public synchronized EmergencyStopResult emergencyStop() {
        List<String> allRuleIds = new ArrayList<String>();
        // Snapshot under the lock so concurrent activate() cannot add profiles
        // whose rules would be missed by the clear().
        List<String> deactivatedProfiles = new ArrayList<String>(activeProfileNames);

        for (String profileName : deactivatedProfiles) {
            ChaosProfile profile = profiles.get(profileName);
            if (profile != null && profile.getRules() != null) {
                for (int i = 0; i < profile.getRules().size(); i++) {
                    allRuleIds.add(generateRuleId(profileName, i));
                }
            }
        }

        // Remove each profile individually (not clear()) so that a concurrent
        // activate() that snuck in after the snapshot is NOT silently wiped —
        // it will remain active and its caller will get a proper ALREADY_ACTIVE
        // result. The snapshot profiles are guaranteed to be removed.
        for (String profileName : deactivatedProfiles) {
            activeProfileNames.remove(profileName);
        }

        return new EmergencyStopResult(deactivatedProfiles, allRuleIds);
    }

    /**
     * Get the list of currently active profile names.
     */
    public List<String> getActiveProfileNames() {
        return new ArrayList<String>(activeProfileNames);
    }

    /**
     * Check if a profile is currently active.
     */
    public boolean isActive(String profileName) {
        return activeProfileNames.contains(profileName);
    }

    /**
     * Get the status of all profiles (active + inactive).
     */
    public List<ProfileStatus> getStatus() {
        List<ProfileStatus> statusList = new ArrayList<ProfileStatus>();
        for (ChaosProfile profile : profiles.values()) {
            boolean active = activeProfileNames.contains(profile.getName());
            int ruleCount = profile.getRules() != null ? profile.getRules().size() : 0;
            statusList.add(new ProfileStatus(profile.getName(), active, ruleCount,
                    profile.getEnvironments()));
        }
        return statusList;
    }

    // ===== Internal helpers =====

    private Rule generateRule(ChaosProfile profile, ChaosRule chaosRule, int index) {
        Rule rule = new Rule();
        rule.setId(generateRuleId(profile.getName(), index));
        rule.setName(chaosRule.getName() != null ? chaosRule.getName()
                : "Chaos: " + profile.getName() + " #" + index);
        rule.setProtocol("http");
        rule.setEnabled(true);
        // H6 fix: read priority from the profile (default 50, configurable).
        rule.setPriority(profile.getPriority()); // Higher priority than normal rules (default 100)

        // Environments from profile
        if (profile.getEnvironments() != null) {
            rule.setEnvironments(new ArrayList<String>(profile.getEnvironments()));
        } else {
            rule.setEnvironments(Collections.<String>emptyList());
        }

        // Tags for identification
        List<String> tags = new ArrayList<String>();
        tags.add("chaos");
        tags.add("chaos-" + profile.getName());
        rule.setTags(tags);

        // Conditions: method + path
        List<MatchCondition> conditions = new ArrayList<MatchCondition>();
        if (chaosRule.getMethod() != null && !chaosRule.getMethod().isEmpty()) {
            conditions.add(MatchCondition.method(chaosRule.getMethod().toUpperCase()));
        }
        if (chaosRule.getPath() != null && !chaosRule.getPath().isEmpty()) {
            // Use regex for path to support pattern matching
            conditions.add(MatchCondition.path("regex", chaosRule.getPath()));
        }
        rule.setConditions(conditions);

        // Fault injection from Chaos rule
        rule.setFaultInjection(chaosRule.getFaultInjection());

        // Default response (used when no fault triggers)
        ResponseEntry entry = new ResponseEntry();
        entry.setStatusCode(200);
        entry.setName("Default (no fault triggered)");
        entry.setBody("{\"message\":\"Chaos profile active — fault may trigger on next request\"}");
        List<ResponseEntry> responses = new ArrayList<ResponseEntry>();
        responses.add(entry);
        rule.setResponses(responses);

        return rule;
    }

    private String generateRuleId(String profileName, int index) {
        // Cap the index suffix to 4 digits to keep rule IDs bounded
        // (code-smell #8). For indices > 9999 only the last 4 digits are
        // used, which is sufficient to distinguish rules within a single
        // profile while preventing unbounded ID growth.
        String suffix = String.valueOf(index);
        if (suffix.length() > 4) {
            suffix = suffix.substring(suffix.length() - 4);
        }
        return CHAOS_RULE_ID_PREFIX + profileName + "-" + suffix;
    }

    // ===== Result classes =====

    /**
     * Result of activating a Chaos profile.
     */
    public static class ActivateResult {
        public enum Status { SUCCESS, NOT_FOUND, ALREADY_ACTIVE }

        private final String profileName;
        private final Status status;
        private final List<Rule> generatedRules;

        private ActivateResult(String profileName, Status status, List<Rule> generatedRules) {
            this.profileName = profileName;
            this.status = status;
            this.generatedRules = generatedRules != null ? generatedRules : Collections.<Rule>emptyList();
        }

        static ActivateResult success(String name, List<Rule> rules) {
            return new ActivateResult(name, Status.SUCCESS, rules);
        }

        static ActivateResult notFound(String name) {
            return new ActivateResult(name, Status.NOT_FOUND, Collections.<Rule>emptyList());
        }

        static ActivateResult alreadyActive(String name) {
            return new ActivateResult(name, Status.ALREADY_ACTIVE, Collections.<Rule>emptyList());
        }

        public String getProfileName() { return profileName; }
        public Status getStatus() { return status; }
        public List<Rule> getGeneratedRules() { return generatedRules; }
        public boolean isSuccess() { return status == Status.SUCCESS; }
    }

    /**
     * Result of deactivating a Chaos profile.
     */
    public static class DeactivateResult {
        public enum Status { SUCCESS, NOT_ACTIVE }

        private final String profileName;
        private final Status status;
        private final List<String> ruleIds;

        private DeactivateResult(String profileName, Status status, List<String> ruleIds) {
            this.profileName = profileName;
            this.status = status;
            this.ruleIds = ruleIds != null ? ruleIds : Collections.<String>emptyList();
        }

        static DeactivateResult success(String name, List<String> ruleIds) {
            return new DeactivateResult(name, Status.SUCCESS, ruleIds);
        }

        static DeactivateResult notActive(String name) {
            return new DeactivateResult(name, Status.NOT_ACTIVE, Collections.<String>emptyList());
        }

        public String getProfileName() { return profileName; }
        public Status getStatus() { return status; }
        public List<String> getRuleIds() { return ruleIds; }
        public boolean isSuccess() { return status == Status.SUCCESS; }
    }

    /**
     * Result of an emergency stop operation.
     */
    public static class EmergencyStopResult {
        private final List<String> deactivatedProfiles;
        private final List<String> ruleIds;

        public EmergencyStopResult(List<String> deactivatedProfiles, List<String> ruleIds) {
            this.deactivatedProfiles = deactivatedProfiles != null ? deactivatedProfiles
                    : Collections.<String>emptyList();
            this.ruleIds = ruleIds != null ? ruleIds : Collections.<String>emptyList();
        }

        public List<String> getDeactivatedProfiles() { return deactivatedProfiles; }
        public List<String> getRuleIds() { return ruleIds; }
    }

    /**
     * Status of a single Chaos profile.
     */
    public static class ProfileStatus {
        private final String name;
        private final boolean active;
        private final int ruleCount;
        private final List<String> environments;

        public ProfileStatus(String name, boolean active, int ruleCount, List<String> environments) {
            this.name = name;
            this.active = active;
            this.ruleCount = ruleCount;
            this.environments = environments != null ? environments : Collections.<String>emptyList();
        }

        public String getName() { return name; }
        public boolean isActive() { return active; }
        public int getRuleCount() { return ruleCount; }
        public List<String> getEnvironments() { return environments; }
    }
}
