package com.baafoo.core.util;

import com.baafoo.core.model.ChaosProfile;
import com.baafoo.core.model.ChaosProfile.ChaosRule;
import com.baafoo.core.model.FaultInjection;
import com.baafoo.core.model.MatchCondition;
import com.baafoo.core.model.ResponseEntry;
import com.baafoo.core.model.Rule;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Chaos engineering profile manager (PRD §6 R-S13).
 *
 * <p>Manages the lifecycle of Chaos profiles: loading from config, activating
 * (generating and tracking fault injection rules), deactivating, and emergency
 * stop. Thread-safe via ConcurrentHashMap for active profile tracking.</p>
 *
 * <p>Profile activation generates Baafoo {@link Rule}s with fault injection
 * configs. The generated rule IDs follow the pattern
 * {@code chaos-{profileName}-{ruleIndex}} for easy identification and cleanup.</p>
 */
public class ChaosManager {

    /** Prefix for rule IDs generated by Chaos profiles */
    public static final String CHAOS_RULE_ID_PREFIX = "chaos-";

    private final Map<String, ChaosProfile> profiles = new ConcurrentHashMap<String, ChaosProfile>();
    private final Set<String> activeProfileNames = Collections.newSetFromMap(
            new ConcurrentHashMap<String, Boolean>());

    /**
     * Register a Chaos profile.
     *
     * @param profile the profile to register; replaces any existing profile with the same name
     */
    public void registerProfile(ChaosProfile profile) {
        if (profile == null || profile.getName() == null || profile.getName().isEmpty()) {
            throw new IllegalArgumentException("Profile name must not be null or empty");
        }
        profiles.put(profile.getName(), profile);
    }

    /**
     * Register multiple profiles at once.
     */
    public void registerProfiles(List<ChaosProfile> profileList) {
        if (profileList == null) return;
        for (ChaosProfile profile : profileList) {
            registerProfile(profile);
        }
    }

    /**
     * Get a registered profile by name.
     */
    public ChaosProfile getProfile(String name) {
        return profiles.get(name);
    }

    /**
     * List all registered profiles.
     */
    public List<ChaosProfile> listProfiles() {
        return new ArrayList<ChaosProfile>(profiles.values());
    }

    /**
     * Activate a Chaos profile, generating fault injection rules.
     *
     * <p>For each {@link ChaosRule} in the profile, a Baafoo {@link Rule} is
     * generated with:
     * <ul>
     *   <li>ID: {@code chaos-{profileName}-{index}}</li>
     *   <li>Conditions: method + path (regex)</li>
     *   <li>Fault injection: from the Chaos rule</li>
     *   <li>Environments: from the profile</li>
     *   <li>A default 200 response (in case no fault triggers)</li>
     * </ul>
     * </p>
     *
     * @param profileName the name of the profile to activate
     * @return list of generated rules (empty if profile not found or already active)
     */
    public ActivateResult activate(String profileName) {
        ChaosProfile profile = profiles.get(profileName);
        if (profile == null) {
            return ActivateResult.notFound(profileName);
        }
        if (activeProfileNames.contains(profileName)) {
            return ActivateResult.alreadyActive(profileName);
        }

        List<Rule> generatedRules = new ArrayList<Rule>();
        List<ChaosRule> chaosRules = profile.getRules();
        if (chaosRules != null) {
            for (int i = 0; i < chaosRules.size(); i++) {
                ChaosRule chaosRule = chaosRules.get(i);
                Rule rule = generateRule(profile, chaosRule, i);
                generatedRules.add(rule);
            }
        }

        activeProfileNames.add(profileName);
        return ActivateResult.success(profileName, generatedRules);
    }

    /**
     * Deactivate a Chaos profile.
     *
     * @param profileName the name of the profile to deactivate
     * @return list of rule IDs that were generated by this profile (for cleanup)
     */
    public DeactivateResult deactivate(String profileName) {
        if (!activeProfileNames.contains(profileName)) {
            return DeactivateResult.notActive(profileName);
        }

        ChaosProfile profile = profiles.get(profileName);
        List<String> ruleIds = new ArrayList<String>();
        if (profile != null && profile.getRules() != null) {
            for (int i = 0; i < profile.getRules().size(); i++) {
                ruleIds.add(generateRuleId(profileName, i));
            }
        }

        activeProfileNames.remove(profileName);
        return DeactivateResult.success(profileName, ruleIds);
    }

    /**
     * Emergency stop: deactivate all active Chaos profiles.
     *
     * @return list of all rule IDs generated by active profiles (for cleanup)
     */
    public EmergencyStopResult emergencyStop() {
        List<String> allRuleIds = new ArrayList<String>();
        List<String> deactivatedProfiles = new ArrayList<String>(activeProfileNames);

        for (String profileName : deactivatedProfiles) {
            ChaosProfile profile = profiles.get(profileName);
            if (profile != null && profile.getRules() != null) {
                for (int i = 0; i < profile.getRules().size(); i++) {
                    allRuleIds.add(generateRuleId(profileName, i));
                }
            }
        }

        activeProfileNames.clear();
        return new EmergencyStopResult(deactivatedProfiles, allRuleIds);
    }

    /**
     * Get the list of currently active profile names.
     */
    public List<String> getActiveProfileNames() {
        return new ArrayList<String>(activeProfileNames);
    }

    /**
     * Check if a profile is currently active.
     */
    public boolean isActive(String profileName) {
        return activeProfileNames.contains(profileName);
    }

    /**
     * Get the status of all profiles (active + inactive).
     */
    public List<ProfileStatus> getStatus() {
        List<ProfileStatus> statusList = new ArrayList<ProfileStatus>();
        for (ChaosProfile profile : profiles.values()) {
            boolean active = activeProfileNames.contains(profile.getName());
            int ruleCount = profile.getRules() != null ? profile.getRules().size() : 0;
            statusList.add(new ProfileStatus(profile.getName(), active, ruleCount,
                    profile.getEnvironments()));
        }
        return statusList;
    }

    // ===== Internal helpers =====

    private Rule generateRule(ChaosProfile profile, ChaosRule chaosRule, int index) {
        Rule rule = new Rule();
        rule.setId(generateRuleId(profile.getName(), index));
        rule.setName(chaosRule.getName() != null ? chaosRule.getName()
                : "Chaos: " + profile.getName() + " #" + index);
        rule.setProtocol("http");
        rule.setEnabled(true);
        rule.setPriority(50); // Higher priority than normal rules (default 100)

        // Environments from profile
        if (profile.getEnvironments() != null) {
            rule.setEnvironments(new ArrayList<String>(profile.getEnvironments()));
        } else {
            rule.setEnvironments(Collections.<String>emptyList());
        }

        // Tags for identification
        List<String> tags = new ArrayList<String>();
        tags.add("chaos");
        tags.add("chaos-" + profile.getName());
        rule.setTags(tags);

        // Conditions: method + path
        List<MatchCondition> conditions = new ArrayList<MatchCondition>();
        if (chaosRule.getMethod() != null && !chaosRule.getMethod().isEmpty()) {
            conditions.add(MatchCondition.method(chaosRule.getMethod().toUpperCase()));
        }
        if (chaosRule.getPath() != null && !chaosRule.getPath().isEmpty()) {
            // Use regex for path to support pattern matching
            conditions.add(MatchCondition.path("regex", chaosRule.getPath()));
        }
        rule.setConditions(conditions);

        // Fault injection from Chaos rule
        rule.setFaultInjection(chaosRule.getFaultInjection());

        // Default response (used when no fault triggers)
        ResponseEntry entry = new ResponseEntry();
        entry.setStatusCode(200);
        entry.setName("Default (no fault triggered)");
        entry.setBody("{\"message\":\"Chaos profile active — fault may trigger on next request\"}");
        List<ResponseEntry> responses = new ArrayList<ResponseEntry>();
        responses.add(entry);
        rule.setResponses(responses);

        return rule;
    }

    private String generateRuleId(String profileName, int index) {
        return CHAOS_RULE_ID_PREFIX + profileName + "-" + index;
    }

    // ===== Result classes =====

    /**
     * Result of activating a Chaos profile.
     */
    public static class ActivateResult {
        public enum Status { SUCCESS, NOT_FOUND, ALREADY_ACTIVE }

        private final String profileName;
        private final Status status;
        private final List<Rule> generatedRules;

        private ActivateResult(String profileName, Status status, List<Rule> generatedRules) {
            this.profileName = profileName;
            this.status = status;
            this.generatedRules = generatedRules != null ? generatedRules : Collections.<Rule>emptyList();
        }

        static ActivateResult success(String name, List<Rule> rules) {
            return new ActivateResult(name, Status.SUCCESS, rules);
        }

        static ActivateResult notFound(String name) {
            return new ActivateResult(name, Status.NOT_FOUND, Collections.<Rule>emptyList());
        }

        static ActivateResult alreadyActive(String name) {
            return new ActivateResult(name, Status.ALREADY_ACTIVE, Collections.<Rule>emptyList());
        }

        public String getProfileName() { return profileName; }
        public Status getStatus() { return status; }
        public List<Rule> getGeneratedRules() { return generatedRules; }
        public boolean isSuccess() { return status == Status.SUCCESS; }
    }

    /**
     * Result of deactivating a Chaos profile.
     */
    public static class DeactivateResult {
        public enum Status { SUCCESS, NOT_ACTIVE }

        private final String profileName;
        private final Status status;
        private final List<String> ruleIds;

        private DeactivateResult(String profileName, Status status, List<String> ruleIds) {
            this.profileName = profileName;
            this.status = status;
            this.ruleIds = ruleIds != null ? ruleIds : Collections.<String>emptyList();
        }

        static DeactivateResult success(String name, List<String> ruleIds) {
            return new DeactivateResult(name, Status.SUCCESS, ruleIds);
        }

        static DeactivateResult notActive(String name) {
            return new DeactivateResult(name, Status.NOT_ACTIVE, Collections.<String>emptyList());
        }

        public String getProfileName() { return profileName; }
        public Status getStatus() { return status; }
        public List<String> getRuleIds() { return ruleIds; }
        public boolean isSuccess() { return status == Status.SUCCESS; }
    }

    /**
     * Result of an emergency stop operation.
     */
    public static class EmergencyStopResult {
        private final List<String> deactivatedProfiles;
        private final List<String> ruleIds;

        public EmergencyStopResult(List<String> deactivatedProfiles, List<String> ruleIds) {
            this.deactivatedProfiles = deactivatedProfiles != null ? deactivatedProfiles
                    : Collections.<String>emptyList();
            this.ruleIds = ruleIds != null ? ruleIds : Collections.<String>emptyList();
        }

        public List<String> getDeactivatedProfiles() { return deactivatedProfiles; }
        public List<String> getRuleIds() { return ruleIds; }
    }

    /**
     * Status of a single Chaos profile.
     */
    public static class ProfileStatus {
        private final String name;
        private final boolean active;
        private final int ruleCount;
        private final List<String> environments;

        public ProfileStatus(String name, boolean active, int ruleCount, List<String> environments) {
            this.name = name;
            this.active = active;
            this.ruleCount = ruleCount;
            this.environments = environments != null ? environments : Collections.<String>emptyList();
        }

        public String getName() { return name; }
        public boolean isActive() { return active; }
        public int getRuleCount() { return ruleCount; }
        public List<String> getEnvironments() { return environments; }
    }
}
