server:
  port: 18083

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USER:nacos}
        password: ${NACOS_PASS:nacos}

management:
  endpoints:
    web:
      exposure:
        include: "*"
