const fs = require('fs');
const zhPath = 'C:/Dev/Projects/Baafoo/web/src/locales/zh-CN.json';
const enPath = 'C:/Dev/Projects/Baafoo/web/src/locales/en.json';
const zh = JSON.parse(fs.readFileSync(zhPath, 'utf8'));
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
delete zh.rules.templates.hint;
delete en.rules.templates.hint;
fs.writeFileSync(zhPath, JSON.stringify(zh, null, 2) + '\n', 'utf8');
fs.writeFileSync(enPath, JSON.stringify(en, null, 2) + '\n', 'utf8');
console.log('zh templates keys:', Object.keys(zh.rules.templates));
console.log('en templates keys:', Object.keys(en.rules.templates));
